[package]
name = "ppserver_def"
version = "0.1.0"
authors = ["范辉 <fanhui.x@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ppcore_def = { path = "../core_def" }
