[package]
name = "ttserver_def"
version = "0.2.9"
authors = ["范辉 <fanhui.x@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ttcore_def = { path = "../core_def" }
